### ISSUE TITLE
Incorrect hash for dynamic CSS files not using contenthash,

### ISSUE THREAD

**Issue by isidrok** [GoogleChromeLabs/prerender-loader#17]
Hi,  when using `prerender-loader` in conjunction with `mini-css-extract-plugin` there is an error loading CSS imported by `dynamic-chunks` when the hashing strategy is different from `contenthash` for that css file.

In that case, `prerender-loader` outputs a link pointing to a CSS file with a different hash. 

Note that this doesn't apply to JS files nor to CSS files imported by the main (entrypoint) chunk.

A full reproduction is in https://github.com/isidrok/prerender-loader-reprod, look at the readme for more information.

The original discussion is in GoogleChromeLabs/critters#7

**Comment by developit** [comment]
This should be fixed now as long as you upgrade to the latest (0.4.4) mini-css-extract-plugin!

**Comment by developit** [comment]
Closing since you gave it a thumbs up - let me know if you're still hitting issues!

**Comment by isidrok** [comment]
Just tried with the new version of mini-css-extract-plugin and neither critters nor prerender-loader output any error but the referenced css file is still incorrect for dynamically imported modules.

If I remove prerender-loader and just use Critters the following error is thrown: 
`TypeError: Cannot read property 'textContent' of undefined`.

The css file referenced in the bundle under the comment `mini-css-extract-plugin CSS loading` is correct though.

After looking at the mini-css-extract-plugin source seems they are handling hashes on the `hashForChunk` and `contentHash`, maybe that happens after prerender-loader does its work, will check later.

**Comment by isidrok** [comment]
Summarizing the previous comment:

Since prerender-loader is creating a new compilation when using a hash different from `contenthash` it changes during that specific build and doesn't reference real assets, which have the hash of the original compilation.

**Comment by developit** [comment]
That makes sense. Perhaps it'd be worth having the plugin warn when `[hash]` is used.
